### ISSUE TITLE
Split out RPC types duplicated between here and terraform into common module

### ISSUE THREAD

**Issue by LorbusChris** [hashicorp/terraform-plugin-sdk#277]
### SDK version
```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.4.0"
}
```

### Description of Problem
Importing and using the `terraform-plugin-sdk` into a project alongside `terraform` causes panics in `gob` and `proto` when the RPC types that are duplicated between those two repos are attempted to be initialized for a second time (namely `tfdiags.rpcFriendlyDiag` and all proto-generated types from `tfplugin5`):
```
panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag
goroutine 1 [running]:
encoding/gob.RegisterName(0x84498da, 0x18, 0x94d9180, 0x0)
	/usr/local/go/src/encoding/gob/type.go:820 +0x55e
encoding/gob.Register(0x94d9180, 0x0)
	/usr/local/go/src/encoding/gob/type.go:874 +0x125
github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags.init.0()
	/go/src/github.com/openshift/installer/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfdiags/rpc_friendly.go:58 +0x36 
```
```
panic: proto: duplicate enum registered: tfplugin5.Diagnostic_Severity

goroutine 1 [running]:
github.com/golang/protobuf/proto.RegisterEnum(...)
        /go/pkg/mod/github.com/golang/protobuf@v1.3.2/proto/properties.go:458
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5.init.0()
```
While I've been made aware that this is generally not a supported use-case, for us over at [OpenShift Installer](https://github.com/openshift/installer) this is a regression from previous behaviour after migrating to the sdk, and makes it impossible for us to import `terraform-plugin-sdk` there as-is.

I do however see ~~two~~ one possible option for a solution here:
1. One would be the deduplication of those types between here and the `terraform` repo, which is probably not a thing that can be done in the short-term.

~~2. The second option is to rename these types (or rather the internal packages containing them, as that means fewer code changes) in this repository. This would solve the panics when initializing the types, as they wouldn't be found to be duplicates by `gob` and `proto` any more. Note that this only requires renaming of the `tfdiags` and `tfplugin5` packages, as other duplicated types do not call into gob/proto for registering and there are no panics.~~

Therefore, my question is, is it possible for you to split out the duplicate code into a common module that would be shared between/impored by both `terraform` and `terraform-plugin-sdk`

**Comment by LorbusChris** [comment]
cc @abhinavdahiya

**Comment by LorbusChris** [comment]
Closing this in favor of https://github.com/hashicorp/terraform/issues/23725
