### ISSUE TITLE
ImportState in First TestStep of TestCase Panics

### ISSUE THREAD

**Issue by bflad** [hashicorp/terraform-plugin-sdk#373]
### SDK version

```
v1.8.0
```

### Relevant provider source code

This is a modified version of the [actual acceptance test](https://github.com/terraform-providers/terraform-provider-aws/blob/c66ae719ddc7beb80a99582eb4b3087ff4107bee/aws/resource_aws_vpc_test.go#L104-L137), just to highlight the scenario.

```go
func TestAccAWSVpc_basic(t *testing.T) {
	var vpc ec2.Vpc
	resourceName := "aws_vpc.test"

	resource.ParallelTest(t, resource.TestCase{
		PreCheck:     func() { testAccPreCheck(t) },
		Providers:    testAccProviders,
		CheckDestroy: testAccCheckVpcDestroy,
		Steps: []resource.TestStep{
			{
				Config: testAccVpcConfig,
				Check: resource.ComposeTestCheckFunc(
					testAccCheckVpcExists(resourceName, &vpc),
					testAccCheckVpcCidr(&vpc, "10.1.0.0/16"),
					testAccMatchResourceAttrRegionalARN(resourceName, "arn", "ec2", regexp.MustCompile(`vpc/vpc-.+`)),
					resource.TestCheckResourceAttr(resourceName, "assign_generated_ipv6_cidr_block", "false"),
					resource.TestMatchResourceAttr(resourceName, "default_route_table_id", regexp.MustCompile(`^rtb-.+`)),
					resource.TestCheckResourceAttr(resourceName, "cidr_block", "10.1.0.0/16"),
					resource.TestCheckResourceAttr(resourceName, "enable_dns_support", "true"),
					resource.TestCheckResourceAttr(resourceName, "instance_tenancy", "default"),
					resource.TestCheckResourceAttr(resourceName, "ipv6_association_id", ""),
					resource.TestCheckResourceAttr(resourceName, "ipv6_cidr_block", ""),
					resource.TestMatchResourceAttr(resourceName, "main_route_table_id", regexp.MustCompile(`^rtb-.+`)),
					testAccCheckResourceAttrAccountID(resourceName, "owner_id"),
				),
				ResourceName:      resourceName,
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}
```

### Terraform Configuration Files

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"
}
```

### Debug Output

```
... provider initialization API calls ...
2020/03/30 20:24:02 [DEBUG] Test: Executing step 0
```

### Expected Behavior

The acceptance testing framework would either run both the apply testing and the import state testing in the same step or produce an appropriate error saying the state is missing or `ImportState` cannot be used in the first `TestStep` of a `TestCase`.

### Actual Behavior

Panic.

```
--- FAIL: TestAccAWSVpc_basic (2.23s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x1bf7175]

goroutine 13 [running]:
testing.tRunner.func1.1(0x6263980, 0xb5b6e80)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:941 +0x3d0
testing.tRunner.func1(0xc0001bb320)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:944 +0x3f9
panic(0x6263980, 0xb5b6e80)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
github.com/hashicorp/terraform-plugin-sdk/helper/resource.testResource(0x6e24fce, 0xc, 0x0, 0x0, 0x0, 0x0, 0x6fa33a9, 0x69, 0xc000585ce0, 0x0, ...)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/resource/testing.go:948 +0x35
github.com/hashicorp/terraform-plugin-sdk/helper/resource.testStepImportState(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/resource/testing_import_state.go:37 +0x1d2e
github.com/hashicorp/terraform-plugin-sdk/helper/resource.Test(0x7cbc7a0, 0xc0001bb320, 0x0, 0xc000b9e6d0, 0xc000818ab0, 0x0, 0x0, 0x720b9b0, 0xc000af7380, 0x1, ...)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/resource/testing.go:626 +0x7b6
github.com/hashicorp/terraform-plugin-sdk/helper/resource.ParallelTest(0x7cbc7a0, 0xc0001bb320, 0x0, 0xc000b9e6d0, 0xc000818ab0, 0x0, 0x0, 0x720b9b0, 0xc000af7380, 0x1, ...)
	/Users/bflad/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.8.0/helper/resource/testing.go:523 +0x94
github.com/terraform-providers/terraform-provider-aws/aws.TestAccAWSVpc_basic(0xc0001bb320)
	/Users/bflad/src/github.com/terraform-providers/terraform-provider-aws-trois/aws/resource_aws_vpc_test.go:108 +0x60a
testing.tRunner(0xc0001bb320, 0x7203c98)
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:992 +0xdc
created by testing.(*T).Run
	/usr/local/Cellar/go/1.14/libexec/src/testing/testing.go:1043 +0x357
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	3.128s
```

### Steps to Reproduce

In the Terraform AWS Provider codebase (with modified test):

```
TF_ACC=1 go test ./aws -v -count 1 -timeout 120m -run='TestAccAWSVpc_basic'
```

### References

- https://github.com/bflad/tfproviderlint/issues/134

**Comment by paddycarver** [comment]
@bflad is this still happening in v2.0.4?

**Comment by bflad** [comment]
Looks like switching to the binary testing framework might have adjusted this to at least report a related error instead of panic:

```
=== CONT  TestAccAWSVpc_basic
    resource_aws_vpc_test.go:108: Resource specified by ResourceName couldn't be found: aws_vpc.test
--- FAIL: TestAccAWSVpc_basic (1.37s)
```

Closing as this is good enough for me!
