### ISSUE TITLE
Value out of range when trying to run plan

### ISSUE THREAD

**Issue by megan07** [hashicorp/terraform-plugin-sdk#469]
### SDK version

```
1.11.0
```

### Relevant provider source code

https://github.com/terraform-providers/terraform-provider-google/blob/v3.22.0/google/resource_big_query_dataset.go

### Terraform Configuration Files

```hcl
provider "google" {
  version = "3.22.0"
  project = var.gke_project
  region  = var.gke_region
}

resource "google_bigquery_dataset" "dataset" {
  dataset_id    = replace("gke_usage_${var.cluster_name}", "-", "_")
  friendly_name = "gke-usage-${var.cluster_name}"
  description   = "GKE usage - ${var.cluster_name}"
  location      = "EU"
  project       = var.gke_project

  labels = {
    env     = var.env
    cluster = var.cluster_name
  }

  access {
    role          = "OWNER"
    special_group = "projectOwners"
  }
  access {
    role          = "READER"
    special_group = "projectReaders"
  }
  access {
    role          = "WRITER"
    special_group = "projectWriters"
  }
}
```

### Debug Output

https://gist.github.com/thecodeassassin/f9e0c436100cefb2028eee96ab9faf18#file-terraform_output-txt-L6228

### Expected Behavior

Plan should be created successfully.

### Actual Behavior

Terraform exists, we found this error:

module..google_bigquery_dataset.dataset: Refreshing state... [id=projects/***/datasets/gke_usage_europe_west]
2020-06-03T15:46:30.339Z [DEBUG] plugin.terraform-provider-google_v3.24.0_x5: panic: Error reading level state: strconv.ParseInt: parsing "1591104108820": value out of range

resulting in:

Error: rpc error: code = Canceled desc = context canceled

### Steps to Reproduce

`terraform plan`

### References

https://github.com/terraform-providers/terraform-provider-google/issues/6518

**Comment by paddycarver** [comment]
Am I right in assuming this only exists on 32 bit systems?

Looks like it's trying to parse a potentially 64 bit integer into an `int`, which would fail on 32 bit systems. But it's [been that way for 6 years](https://github.com/hashicorp/terraform-plugin-sdk/commit/e04069d9d45ae9a0f81f16c9e42ddf3d6a5d11d0#diff-cc1a59d897b4600df59be303966de110R123), so I'm surprised we've not heard more about it earlier.

I'm guessing, as I don't actually see it, but I'm guessing the field that is throwing the error is one of the timestamp fields, as it has been more milliseconds since the epoch than can fit in an int32.

The solution to this is to store ints internally in an architecture independent int64 type, but I don't know what that will mess up. Raising with the team.

**Comment by paddycarver** [comment]
(Worth noting: storing as seconds instead of milliseconds will buy just under 18 years, as a workaround. Switching to an int64 internally will buy us some 200 million years. Paddy-200-million-years-from-now can deal with converting to int128.)

**Comment by neb14** [comment]
I'm running into something very similar.  What is the fix?
```
panic: Error reading level state: strconv.ParseInt: parsing "2768156499462823400": value out of range

```

**Comment by neb14** [comment]
here is the complete trace
```
module.gcp-fedex-us-prod-vm.google_compute_url_map.conduit-web-https-url-map: Refreshing state... [id=conduit-web-https-url-map]

Error: rpc error: code = Unavailable desc = transport is closing


panic: Error reading level state: strconv.ParseInt: parsing "2768156499462823400": value out of range
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: goroutine 966 [running]:
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).get(0xb63b540, 0xbb00b48, 0x1, 0x1, 0xb719e08, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go:529 +0x293
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*ResourceData).State(0xb63b540, 0xb730150)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource_data.go:327 +0x298
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).ShimInstanceStateFromValue(0xb536b40, 0x9cd6000, 0xbb001e8, 0x95a3380, 0xb9b71a0, 0x9cd6000, 0xbb001e8, 0x95a3380)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform-plugin-sdk/helper/schema/resource.go:191 +0x157
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xb519158, 0x9cd5860, 0xb9b6140, 0xb7300c0, 0xb519158, 0x1, 0xb9b6140)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin/grpc_provider.go:510 +0x1d3
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x9904380, 0xb519158, 0x9cd5860, 0xb9b6140, 0xb730090, 0x0, 0x9cd5860, 0xb9b6140, 0xb41a000, 0x267)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5/tfplugin5.pb.go:3153 +0x195
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: google.golang.org/grpc.(*Server).processUnaryRPC(0xb40a0f0, 0x9ce0f20, 0xb5fa100, 0xb974000, 0xb517aa0, 0xa8fa088, 0x0, 0x0, 0x0)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/google.golang.org/grpc/server.go:995 +0x4a7
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: google.golang.org/grpc.(*Server).handleStream(0xb40a0f0, 0x9ce0f20, 0xb5fa100, 0xb974000, 0x0)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/google.golang.org/grpc/server.go:1275 +0xae4
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xb96f6d0, 0xb40a0f0, 0x9ce0f20, 0xb5fa100, 0xb974000)
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/google.golang.org/grpc/server.go:710 +0x8b
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-10-30T14:33:05.014-0500 [DEBUG] plugin.terraform-provider-google_v2.20.3_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-google/vendor/google.golang.org/grpc/server.go:708 +0x7f
2020-10-30T14:33:05.018-0500 [DEBUG] plugin: plugin process exited: path=/home/ben/kenna/repos/terraform/deployments/gcp/fedex/us/prod/.terraform/plugins/linux_386/terraform-provider-google_v2.20.3_x4 pid=306327 error="exit status 2"
2020/10/30 14:33:05 [ERROR] module.gcp-fedex-us-prod-vm: eval: *terraform.EvalRefresh, err: rpc error: code = Unavailable desc = transport is closing
2020/10/30 14:33:05 [ERROR] module.gcp-fedex-us-prod-vm: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/10/30 14:33:05 [TRACE] [walkRefresh] Exiting eval tree: module.gcp-fedex-us-prod-vm.google_compute_url_map.conduit-web-https-url-map
2020/10/30 14:33:05 [TRACE] vertex "module.gcp-fedex-us-prod-vm.google_compute_url_map.conduit-web-https-url-map": visit complete
2020/10/30 14:33:05 [TRACE] vertex "module.gcp-fedex-us-prod-vm.google_compute_url_map.conduit-web-https-url-map": dynamic subgraph encountered errors
2020/10/30 14:33:05 [TRACE] vertex "module.gcp-fedex-us-prod-vm.google_compute_url_map.conduit-web-https-url-map": visit complete
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "module.gcp-fedex-us-prod-vm.google_compute_target_https_proxy.conduit-web-https-target-proxy" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "module.gcp-fedex-us-prod-vm.google_compute_target_http_proxy.conduit-web-http-target-proxy" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "module.gcp-fedex-us-prod-vm.google_compute_global_forwarding_rule.conduit-web-https-forwarding-rule" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "module.gcp-fedex-us-prod-vm.google_compute_global_forwarding_rule.conduit-web-http-forwarding-rule" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "module.gcp-fedex-us-prod-vm.google_dns_record_set.conduit_lb_dns" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "module.gcp-fedex-us-prod-vm.google_dns_record_set.wildcard_dns" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "provider.google (close)" errored, so skipping
2020/10/30 14:33:05 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-10-30T14:33:05.242-0500 [DEBUG] plugin: plugin exited
```

**Comment by pop** [comment]
FWIW I've seen a similar error running on an AWS Graviton (ARM64) host. The error is:

```
2021-07-01T16:47:31.346Z [DEBUG] plugin.terraform-provider-aws_v3.47.0_x5: panic: Error reading level state: strconv.ParseInt: parsing "76756041728": value out of range
```

Where `76756041728` seems to be the value for `aws_efs_file_system.foo.size_in_bytes[0].value`.

I tested a simple go program that ran `strconv.ParseInt("76756041728", 10, 64)` on the same host and it didn't return an error.

**Comment by paddycarver** [comment]
That's very bizarre, because that code on that same host should exhibit the same error if it relates to this error...

**Comment by pop** [comment]
Update: I dug into the issue and for some reason `terraform` is choosing to download the 32bit version of the `aws` provider 🙃
Any idea how I can force it to download the 64bit version instead?

Context: I'm running terraform `v0.13.7` for the time being.

**Comment by paddycarver** [comment]
I think that'd be an issue for https://github.com/hashicorp/terraform/issues, sorry :(

**Comment by pop** [comment]
My issue seems to be a problem with `tfenv`. It defaults to downloading 32bit arm instead of 64bit. [Link Here](https://github.com/tfutils/tfenv/blob/43e0aad9fbc640fc0c6929dda10e54c7300ffe63/README.md#tfenv_arch).

**Comment by bflad** [comment]
@megan07 is this still an issue for you?
