### ISSUE TITLE
panic: can't convert []string{"localhost:9092"} to cty.Value

### ISSUE THREAD

**Issue by Mongey** [hashicorp/terraform-plugin-sdk#480]
### SDK version
```
{
  "Path": "github.com/hashicorp/terraform-plugin-sdk",
  "Version": "v1.14.0"
}

```

### Relevant provider source code

```go
func Provider() terraform.ResourceProvider {
	return &schema.Provider{
		Schema: map[string]*schema.Schema{
			"bootstrap_servers": {
				Type:        schema.TypeList,
				Elem:        &schema.Schema{Type: schema.TypeString},
				DefaultFunc: envDefaultListFunc("KAFKA_BOOTSTRAP_SERVERS", nil),
				Required:    true,
				Description: "A list of Kafka brokers",
			},
		},
	}
}

func envDefaultListFunc(k string, dv interface{}) schema.SchemaDefaultFunc {
	return func() (interface{}, error) {
		if v := os.Getenv(k); v != "" {
			return strings.Split(v, ","), nil
		}

		return dv, nil
	}
}


```

### Terraform Configuration Files

```hcl
provider "kafka" {}
```

`KAFKA_BOOTSTRAP_SERVERS=localhost:9092 terraform refresh`

### Debug Output

```
2020/06/23 15:03:33 [INFO] Terraform version: 0.12.26  
2020/06/23 15:03:33 [INFO] Go runtime version: go1.12.13
2020/06/23 15:03:33 [INFO] CLI args: []string{"/usr/local/Cellar/tfenv/2.0.0/versions/0.12.26/terraform", "refresh"}
2020/06/23 15:03:33 [DEBUG] Attempting to open CLI config file: /Users/conor.mongey/.terraformrc
2020/06/23 15:03:33 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2020/06/23 15:03:33 [DEBUG] checking for credentials in "/Users/conor.mongey/.terraform.d/plugins"
2020/06/23 15:03:33 [INFO] CLI command args: []string{"refresh"}
2020/06/23 15:03:33 [WARN] Log levels other than TRACE are currently unreliable, and are supported only for backward compatibility.
  Use TF_LOG=TRACE to see Terraform's internal logs.
  ----
2020/06/23 15:03:33 [TRACE] Meta.Backend: no config given or present on disk, so returning nil config
2020/06/23 15:03:33 [TRACE] Meta.Backend: backend has not previously been initialized in this working directory
2020/06/23 15:03:33 [DEBUG] New state was assigned lineage "d7b603d0-0375-d5fb-ae7d-a9b3068f5124"
2020/06/23 15:03:33 [TRACE] Meta.Backend: using default local state only (no backend configuration, and no existing initialized backend)
2020/06/23 15:03:33 [TRACE] Meta.Backend: instantiated backend of type <nil>
2020/06/23 15:03:33 [DEBUG] checking for provider in "."
2020/06/23 15:03:33 [DEBUG] checking for provider in "/usr/local/Cellar/tfenv/2.0.0/versions/0.12.26"
2020/06/23 15:03:33 [DEBUG] checking for provider in ".terraform/plugins/darwin_amd64"
2020/06/23 15:03:33 [DEBUG] checking for provider in "/Users/conor.mongey/.terraform.d/plugins"
2020/06/23 15:03:33 [WARN] found legacy provider "terraform-provider-kafka"
....
2020-06-23T15:03:33.834+0100 [INFO]  plugin: configuring client automatic mTLS
2020-06-23T15:03:33.857+0100 [DEBUG] plugin: starting plugin: path=/Users/conor.mongey/.terraform.d/plugins/terraform-provider-kafka args=[/Users/conor.mongey/.terraform.d/plugins/terraform-provider-kafka]
2020-06-23T15:03:33.861+0100 [DEBUG] plugin: plugin started: path=/Users/conor.mongey/.terraform.d/plugins/terraform-provider-kafka pid=44190
2020-06-23T15:03:33.861+0100 [DEBUG] plugin: waiting for RPC address: path=/Users/conor.mongey/.terraform.d/plugins/terraform-provider-kafka
2020-06-23T15:03:33.880+0100 [INFO]  plugin.terraform-provider-kafka: configuring server automatic mTLS: timestamp=2020-06-23T15:03:33.880+0100
2020-06-23T15:03:33.905+0100 [DEBUG] plugin: using plugin: version=5
2020-06-23T15:03:33.905+0100 [DEBUG] plugin.terraform-provider-kafka: plugin address: address=/var/folders/1l/httr6c_533d4x4sg6xvj9w4r0000gn/T/plugin560421605 network=unix timestamp=2020-06-23T15:03:33.905+0100
2020/06/23 15:03:33 [TRACE] BuiltinEvalContext: Initialized "kafka" provider for provider.kafka
2020/06/23 15:03:33 [TRACE] <root>: eval: terraform.EvalNoop
2020/06/23 15:03:33 [TRACE] <root>: eval: *terraform.EvalOpFilter
2020/06/23 15:03:33 [TRACE] <root>: eval: *terraform.EvalSequence
2020-06-23T15:03:33.955+0100 [TRACE] plugin.stdio: waiting for stdio data
2020/06/23 15:03:33 [TRACE] <root>: eval: *terraform.EvalGetProvider
2020/06/23 15:03:33 [TRACE] <root>: eval: *terraform.EvalValidateProvider
2020/06/23 15:03:33 [TRACE] buildProviderConfig for provider.kafka: using explicit config only
2020/06/23 15:03:33 [TRACE] GRPCProvider: GetSchema
2020/06/23 15:03:33 [TRACE] GRPCProvider: PrepareProviderConfig
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: panic: can't convert []string{"localhost:9092"} to cty.Value
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: goroutine 52 [running]:
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/hashicorp/terraform-plugin-sdk/internal/configs/hcl2shim.HCL2ValueFromConfigValue(0x1b39600, 0xc00048a540, 0xc00048a540, 0x0, 0x0, 0xc0000385ec)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/configs/hcl2shim/values.go:228 +0x805
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).PrepareProviderConfig.func1(0xc0005c8230, 0x1, 0x1, 0x204df00, 0xc0000338d0, 0x0, 0x0, 0x204ddc0, 0xc0000385eb, 0x0, ...)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:144 +0x1bc
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/zclconf/go-cty/cty.transform(0xc0005c8230, 0x1, 0x1, 0x204df00, 0xc0000338d0, 0x0, 0x0, 0xc0004fdaf0, 0x0, 0x0, ...)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/walk.go:181 +0xe9
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/zclconf/go-cty/cty.transform(0x0, 0x0, 0x0, 0x204dec0, 0xc00011a030, 0x1bbd9c0, 0xc000510d80, 0xc000019af0, 0x0, 0x0, ...)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/walk.go:168 +0xf02
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/zclconf/go-cty/cty.Transform(0x204dec0, 0xc00011a030, 0x1bbd9c0, 0xc000510d80, 0xc0004fdaf0, 0x204dec0, 0xc00011a030, 0x1bbd9c0, 0xc000510d80, 0x0, ...)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/zclconf/go-cty@v1.2.1/cty/walk.go:89 +0x77
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).PrepareProviderConfig(0xc000652008, 0x204d0c0, 0xc000209bf0, 0xc000209c20, 0xc000652008, 0xc000209bf0, 0xc000082b78)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/helper/plugin/grpc_provider.go:102 +0x1e9
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_PrepareProviderConfig_Handler(0x1cecac0, 0xc000652008, 0x204d0c0, 0xc000209bf0, 0xc000662540, 0x0, 0x204d0c0, 0xc000209bf0, 0xc00004e880, 0xcf6)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/github.com/hashicorp/terraform-plugin-sdk@v1.14.0/internal/tfplugin5/tfplugin5.pb.go:3179 +0x217
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: google.golang.org/grpc.(*Server).processUnaryRPC(0xc000702480, 0x2058b40, 0xc000703500, 0xc000122200, 0xc0001966f0, 0x2809d98, 0x0, 0x0, 0x0)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1024 +0x501
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: google.golang.org/grpc.(*Server).handleStream(0xc000702480, 0x2058b40, 0xc000703500, 0xc000122200, 0x0)
2020-06-23T15:03:33.959+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:1313 +0xd3d
2020-06-23T15:03:33.960+0100 [DEBUG] plugin.terraform-provider-kafka: google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00065e000, 0xc000702480, 0x2058b40, 0xc000703500, 0xc000122200)
2020-06-23T15:03:33.960+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:722 +0xa1
2020-06-23T15:03:33.960+0100 [DEBUG] plugin.terraform-provider-kafka: created by google.golang.org/grpc.(*Server).serveStreams.func1
2020-06-23T15:03:33.960+0100 [DEBUG] plugin.terraform-provider-kafka: 	/Users/conor.mongey/go/pkg/mod/google.golang.org/grpc@v1.27.1/server.go:720 +0xa1
2020-06-23T15:03:33.961+0100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020/06/23 15:03:33 [WARN] <root>: eval: *terraform.EvalValidateProvider, non-fatal err: rpc error: code = Unavailable desc = transport is closing
2020/06/23 15:03:33 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/06/23 15:03:33 [ERROR] <root>: eval: *terraform.EvalOpFilter, err: rpc error: code = Unavailable desc = transport is closing
2020/06/23 15:03:33 [ERROR] <root>: eval: *terraform.EvalSequence, err: rpc error: code = Unavailable desc = transport is closing
2020/06/23 15:03:33 [TRACE] [walkValidate] Exiting eval tree: provider.kafka
2020/06/23 15:03:33 [TRACE] vertex "provider.kafka": visit complete
2020/06/23 15:03:33 [TRACE] dag/walk: upstream of "kafka_acl.global" errored, so skipping
2020/06/23 15:03:33 [TRACE] dag/walk: upstream of "kafka_acl.test" errored, so skipping
2020/06/23 15:03:33 [TRACE] dag/walk: upstream of "kafka_topic.syslog" errored, so skipping
2020/06/23 15:03:33 [TRACE] dag/walk: upstream of "meta.count-boundary (EachMode fixup)" errored, so skipping
2020/06/23 15:03:33 [TRACE] dag/walk: upstream of "provider.kafka (close)" errored, so skipping
2020/06/23 15:03:33 [TRACE] dag/walk: upstream of "root" errored, so skipping
2020-06-23T15:03:33.963+0100 [DEBUG] plugin: plugin process exited: path=/Users/conor.mongey/.terraform.d/plugins/terraform-provider-kafka pid=44190 error="exit status 2"
2020/06/23 15:03:33 [TRACE] statemgr.Filesystem: removing lock metadata file .terraform.tfstate.lock.info
2020/06/23 15:03:33 [TRACE] statemgr.Filesystem: unlocking terraform.tfstate using fcntl flock
2020-06-23T15:03:33.963+0100 [DEBUG] plugin: plugin exited

```

### Expected Behavior
The provider has it's bootstrap_servers set to `[]string{"localhost:9092"}`

### Actual Behavior
It panics

### Steps to Reproduce
1. `KAFKA_BOOTSTRAP_SERVERS=localhost:9092 terraform refresh`

### References
- https://github.com/Mongey/terraform-provider-kafka/pull/131

**Comment by paddycarver** [comment]
Hi @Mongey, that's certainly not good. Sorry about that. Do you know when in the 1.X series this started happening, to help us try and pinpoint a cause?

**Comment by Mongey** [comment]
👋 @paddycarver  

tbh, I don't think this has ever worked. I tried with `v1.0`, and updated to `v1.14.0` hoping that it fixed it 😅. It's also totally possible / probable that I'm doing something wrong 😬

**Comment by paddycarver** [comment]
I know it's annoying, but have you tried making it return an `[]interface{}` instead of a `[]string`?

**Comment by realn0whereman** [comment]
That did it for me, in the test that uses TestResourceDataRaw, I made the mock schema coming in use []interface{} instead of []string{} and it worked

**Comment by bflad** [comment]
I believe this has been answered with https://github.com/hashicorp/terraform-plugin-sdk/issues/480#issuecomment-650357763, but please create a new issue if not.
