### ISSUE TITLE
Provisioners inside my provider -> panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag"

### ISSUE THREAD

**Issue by DavidGOrtega** [hashicorp/terraform-plugin-sdk#664]
Im trying to use provisioners in my provider source code. Seems that I can't invoke them despite that isolated tests seems to be working.

```go
c := terraform.NewResourceConfigRaw(map[string]interface{}{
			"command": "echo 'Hello world'",
		})
		p := localexec.Provisioner()
		if err := p.Apply(new(terraform.MockUIOutput), nil, c); err != nil {
			diags = append(diags, diag.Diagnostic{
				Severity: diag.Error,
				Summary:  fmt.Sprintf("err: %v", err),
			})
		}
```

```
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: panic: gob: registering duplicate types for "*tfdiags.rpcFriendlyDiag": *tfdiags.rpcFriendlyDiag != *tfdiags.rpcFriendlyDiag
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: 
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: goroutine 1 [running]:
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: encoding/gob.RegisterName(0x1e27c50, 0x18, 0x20241e0, 0x0)
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: 	/usr/local/Cellar/go/1.15/libexec/src/encoding/gob/type.go:820 +0x53f
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: encoding/gob.Register(0x20241e0, 0x0)
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: 	/usr/local/Cellar/go/1.15/libexec/src/encoding/gob/type.go:874 +0x12c
2020-12-18T12:33:08.144+0100 [DEBUG] plugin.terraform-provider-iterative: github.com/hashicorp/terraform/tfdiags.init.0()
```

**Comment by xescugc** [comment]
It's this same issue https://github.com/hashicorp/terraform-plugin-sdk/issues/268#issuecomment-562667048

**Comment by bflad** [comment]
Hi @DavidGOrtega 👋  Thanks for raising this. As @xescugc mentions above, this relates to #268.

More explicitly though, the current design of this SDK is not intended for importing, using, or implementing provisioner code. While it may work in some limited scenarios, the maintainers here cannot provide any support for this type of development and cannot ensure any scenarios that do work will continue to do so into the future. Most uses of provisioners [should be avoided](https://www.terraform.io/language/resources/provisioners/syntax) and typically can be replaced by creating managed resources that use the `Create`, etc. fields to perform the same logic.

Since this is not functionality we intend to support, I'm going to close this out. Thanks again though for bringing this up.
